exclude any files folder starting with a .

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -37,7 +37,7 @@ orbs:
             default: 0
         steps:
           - checkout
-          - run: zip -r repo.zip .
+          - run: zip -r repo.zip . -x .*
           - auth:
               pc_username: <<parameters.pc_username>>
               pc_password: <<parameters.pc_password>>
@@ -94,36 +94,39 @@ orbs:
                 echo "response: " $response
                 result="$(echo "$response" | jq -r '.result.is_successful')"
                 echo "result: " $result
-                matched="$(echo "$response" | jq -r '.result.rules_matched')"
-                stats="$(echo "$response" | jq -r '.result.severity_stats')"
-                echo "stats: " $stats
-                mkdir results
-                echo $matched | jq -r '(["FILES","NAME","SEVERITY"] | (., map(length*"-"))), (.[] | [.files[0], .name, .severity]) |@tsv'> results/scan_results.csv
-                echo "<html>" ; echo "<body>" ; echo "<table>" ; while read INPUT ; do echo "<tr><td>${INPUT//,/</td><td>}</td></tr>" ; done < results/scan_results.csv ; echo "</table>"; echo "</body>" ; echo "</html>"
-                (echo "<html>" ;
-                   echo "<body>" ;
-                     echo "<table>" ;
-                       while read INPUT ;
-                         do
-                           echo "<tr><td>${INPUT//,/</td><td>}</td></tr>" ;
-                         done < results/scan_results.csv ;
-                     echo "</table>";
-                   echo "</body>" ;
-                 echo "</html>") >results/results.html
-                 high="$(echo "$stats" | jq -r '.high')"
-                 med="$(echo "$stats" | jq -r '.medium')"
-                 low="$(echo "$stats" | jq -r '.low')"
-                 if [[ $matched != "" ]]
-                 then
-                   if [[ ( "$high" -ge <<parameters.high_cve>> )  || ( "$medium" -ge <<parameters.medium_cve>> ) || ( "$low" -ge <<parameters.low_cve>> ) ]]
+                if [[ $result=="success" ]]
+                then
+                  matched="$(echo "$response" | jq -r '.result.rules_matched')"
+                  stats="$(echo "$response" | jq -r '.result.severity_stats')"
+                  echo "stats: " $stats
+                  mkdir results
+                  echo $matched | jq -r '(["FILES","NAME","SEVERITY"] | (., map(length*"-"))), (.[] | [.files[0], .name, .severity]) |@tsv'> results/scan_results.csv
+                  echo "<html>" ; echo "<body>" ; echo "<table>" ; while read INPUT ; do echo "<tr><td>${INPUT//,/</td><td>}</td></tr>" ; done < results/scan_results.csv ; echo "</table>"; echo "</body>" ; echo "</html>"
+                  (echo "<html>" ;
+                     echo "<body>" ;
+                       echo "<table>" ;
+                         while read INPUT ;
+                           do
+                             echo "<tr><td>${INPUT//,/</td><td>}</td></tr>" ;
+                           done < results/scan_results.csv ;
+                       echo "</table>";
+                     echo "</body>" ;
+                   echo "</html>") >results/results.html
+                   high="$(echo "$stats" | jq -r '.high')"
+                   med="$(echo "$stats" | jq -r '.medium')"
+                   low="$(echo "$stats" | jq -r '.low')"
+                   if [[ $matched != "" ]]
                    then
-                     echo "The build failed because the vulnerability count crossed the threshold values."
-                     echo "Statastics: " $stats
-                     exit 1;
+                     if [[ ( "$high" -ge <<parameters.high_cve>> )  || ( "$medium" -ge <<parameters.medium_cve>> ) || ( "$low" -ge <<parameters.low_cve>> ) ]]
+                     then
+                       echo "The build failed because the vulnerability count crossed the threshold values."
+                       echo "Statastics: " $stats
+                       exit 1;
+                     fi
                    fi
-                 fi
-                 echo "Build successful. All the vulnerability count parameters are under threshold value."
-                 echo "Statastics: \n" $stats
+                   echo "Build successful. All the vulnerability count parameters are under threshold value."
+                   echo "Statastics: \n" $stats
+                fi  
           - store_artifacts:
               path: results/results.html
     executors:
