Reformatting of code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -121,42 +121,42 @@ orbs:
                 if [[ $result ]]
                 then
                   matched="$(echo "$response" | jq -r '.result.rules_matched')"
-                 if [[ $matched != "" ]]
-                 then
-                  stats="$(echo "$response" | jq -r '.result.severity_stats')"
-                  echo "stats: " $stats
-                  mkdir results
-                  echo $matched | jq -r '(["SEVERITY","NAME","FILES"] | (., map(length*"-"))), (.[] | [.severity, .name, .files[0]]) |@tsv'> results/scan_results.csv
-                  head -n 1 results/scan_results.csv > results/scan.csv && tail -n +2 results/scan_results.csv | sort -t "|" -k 1 >> results/scan.csv
-                  #cat results/scan.csv | sed 's/,/ ,/g' | column -t -s, | less -S
-                  #cat results/scan.csv | column -t -s, | less -S
-                  echo "<html>" ; echo "<body>" ; echo "<table>" ; while read INPUT ; do echo "<tr><td>${INPUT//,/</td><td>}</td></tr>" ; done < results/scan_results.csv ; echo "</table>"; echo "</body>" ; echo "</html>"
-                  (echo "<html>" ;
-                     echo "<body>" ;
-                       echo "<table>" ;
-                         while read INPUT ;
-                           do
-                             echo "<tr><td>${INPUT//,/</td><td>}</td></tr>" ;
-                           done < results/scan_results.csv ;
-                       echo "</table>";
-                     echo "</body>" ;
-                   echo "</html>") >results/results.html
-                   high="$(echo "$stats" | jq -r '.high')"
-                   med="$(echo "$stats" | jq -r '.medium')"
-                   low="$(echo "$stats" | jq -r '.low')"
+                  if [[ $matched != "" ]]
+                  then
+                    stats="$(echo "$response" | jq -r '.result.severity_stats')"
+                    echo "stats: " $stats
+                    mkdir results
+                    echo $matched | jq -r '(["SEVERITY","NAME","FILES"] | (., map(length*"-"))), (.[] | [.severity, .name, .files[0]]) |@tsv'> results/scan_results.csv
+                    head -n 1 results/scan_results.csv > results/scan.csv && tail -n +2 results/scan_results.csv | sort -t "|" -k 1 >> results/scan.csv
+                    #cat results/scan.csv | sed 's/,/ ,/g' | column -t -s, | less -S
+                    #cat results/scan.csv | column -t -s, | less -S
+                    echo "<html>" ; echo "<body>" ; echo "<table>" ; while read INPUT ; do echo "<tr><td>${INPUT//,/</td><td>}</td></tr>" ; done < results/scan_results.csv ; echo "</table>"; echo "</body>" ; echo "</html>"
+                    (echo "<html>" ;
+                       echo "<body>" ;
+                         echo "<table>" ;
+                           while read INPUT ;
+                             do
+                               echo "<tr><td>${INPUT//,/</td><td>}</td></tr>" ;
+                             done < results/scan_results.csv ;
+                         echo "</table>";
+                       echo "</body>" ;
+                     echo "</html>") >results/results.html
+                     high="$(echo "$stats" | jq -r '.high')"
+                     med="$(echo "$stats" | jq -r '.medium')"
+                     low="$(echo "$stats" | jq -r '.low')"
        
-                   if [[ ( "$high" -ge <<parameters.high_cve>> )  || ( "$medium" -ge <<parameters.medium_cve>> ) || ( "$low" -ge <<parameters.low_cve>> ) ]]
-                   then
-                     echo "The build failed because the vulnerability count crossed the threshold values."
-                     echo "Statastics: " $stats
-                     exit 1;
+                     if [[ ( "$high" -ge <<parameters.high_cve>> )  || ( "$medium" -ge <<parameters.medium_cve>> ) || ( "$low" -ge <<parameters.low_cve>> ) ]]
+                     then
+                       echo "The build failed because the vulnerability count crossed the threshold values."
+                       echo "Statastics: " $stats
+                       exit 1;
+                     fi
                    fi
-                 fi
-                 echo "Build successful. All the vulnerability count parameters are under threshold value."
-                 echo "Statastics: \n" $stats
-              else
-                echo "$(echo "$response" | jq -r '.result.is_successful')"
-              fi  
+                   echo "Build successful. All the vulnerability count parameters are under threshold value."
+                   echo "Statastics: \n" $stats
+                else
+                  echo "$(echo "$response" | jq -r '.result.is_successful')"
+                fi  
           - store_artifacts:
               path: results/scan.csv
     executors:
